### ISSUE TITLE
support for AS150

### ISSUE THREAD

**Issue by pontos-dev** [Michsior14/ha-venta#8]
I love your integration, I have waited on this in a long time so.... thank you very much

But now I will ask you if it's possible to support my Venta AirSense150 sensor, there are so many sensors in it I will love to have in HA

**Comment by Michsior14** [comment]
Hey! That could be done but first we need some details regarding your device. Do you know if it exposes REST API or it's fully UDP based communication? Additionally full response like in e.g https://github.com/Michsior14/ha-venta/issues/1#issue-2036110913 would be much appreciated.

**Comment by pontos-dev** [comment]
Uhh... How can i find out if its rest api or udp ? 
I don't know much about these things

I have tried to make a port scan on my network, and under the unit the port scanner only mentions tcp port 80
And the device exposes a webui with graphs, I don't know if it helps, but maybe you can suggest some commands I can send  to the unit for some answer from the device

**Comment by Michsior14** [comment]
Take a picture of the webui and post it here if possible. Afterwards try those commands and share the results:

```sh
curl -H "Content-Type: application/json" -X POST "$VENTA_LOCAL_IP/api/telemetry?request=set"
```

```sh
curl -H "Content-Type: application/json" -X POST "$VENTA_LOCAL_IP/datastructure"
```

**Comment by johan-de-jong** [comment]
I hope this helps. My Venta AirSense 150 Pro reports:
<pre>
$ curl -s http://AirSense-xxxxxxxx.fritz.box/sensordata.json
{
        "Header":{
                "DeviceId":"40:91:51:xx:xx:xx",
                "DeviceType":150,
                "ProtocolV":"3"
        },
        "Info":{
                "FirmwareVersion":"0.2-cb32b89-Nov 16 2021",
                "CertificateSHA1":"191ebc14e6b0d72785da806bc0f52e57a3258e59"
        },
        "Measure":{
                "Time":1708357837,
                "Temperature":19.50,
                "Humidity":61.29,
                "Co2":746.00,
                "Voc":0.00,
                "Hcho":5.80,
                "Pm1u0":0.00,
                "Pm2u5":0.00,
                "Pm10u":0.00,
                "Particles0u3":8.00,
                "Particles0u5":0.00,
                "Particles1u0":0.00,
                "Particles2u5":0.00,
                "Particles5u0":0.00,
                "Particles10u":0.00,
                "SensorStatus":"0000001F"
        }
}
</pre>

**Comment by Michsior14** [comment]
@johan-de-jong Thanks for the details. Will try to add this device shortly ;)

**Comment by johan-de-jong** [comment]
As far as I know firmware "0.2-cb32b89-Nov 16 2021" is the most common release. Release "0.2-c5a4e85-Dec 20 2021" was provided to me by Venta support to be installed manually. The AirSense is not automatically pushed version "0.2-c5a4e85-Dec 20 2021".

I captured the output below last May; and decided to use the old firmware instead.

The JSON output is a little bit different in the latest "Dec 20 2021" release. The "Pm1u0", "Pm2u5" and "Pm10u" are now always '0' for me. Apparently they came up with a new formula to convert the particle count to µg/m³ and store the result in "PmCalc1u0", "PmCalc2u5" and "PmCalc10u" instead.

The PM sensor JSON output of the original "Dec 20 2021" release and the app match exactly. The PM sensor JSON output of the newer "Dec 20 2021" release and the app are not always the same. Perhaps the app/cloud takes the Particles[x]u[y] values and uses those to calculate µg/m³ values (and ignore PmCalc[x]u[y] values)?

How do you want to deal with this? Support only the original "0.2-cb32b89-Nov 16 2021" release, or both?

<pre>
{
  "Header": {
    "DeviceId": "40:91:51:xx:xx:xx",
    "DeviceType": 150,
    "ProtocolV": "3"
  },
  "Info": {
    "FirmwareVersion": "0.2-c5a4e85-Dec 20 2021",
    "CertificateSHA1": "191ebc14e6b0d72785da806bc0f52e57a3258e59"
  },
  "Measure": {
    "Time": 1684930262,
    "Temperature": 22.10,
    "Humidity": 45.00,
    "Co2": 443.00,
    "Voc": 21.00,
    "Hcho": 2.60,
    "Pm1u0": 0.00,
    "Pm2u5": 0.00,
    "Pm10u": 0.00,
    "Particles0u3": 30.00,
    "Particles0u5": 5.00,
    "Particles1u0": 1.00,
    "Particles2u5": 0.00,
    "Particles5u0": 0.00,
    "Particles10u": 0.00,
    "PmCalc1u0": 1.76,
    "PmCalc2u5": 0.00,
    "PmCalc10u": 0.00,
    "SensorStatus": "0000001F"
  }
}
</pre>

**Comment by Michsior14** [comment]
Released as [v0.5.1-beta.1](https://github.com/Michsior14/ha-venta/releases/tag/v0.5.1-beta.1). Please give it a try ;)

**Comment by johan-de-jong** [comment]
Even though the Venta AirSense 150 Pro advertises "ProtocolV":"3", it does not respond to a POST /api/telemetry request.

As far as I know the AirSense 150 Pro only responds to a GET /sensordata.json request. See curl example in earlier comment.

Currently I get a "Failed to connect" error when I try to add the AirSense 150 Pro.

**Comment by Michsior14** [comment]
Ohh, I assumed it will work with the same endpoints in case of v3 :/ You also mentioned `/datastructure`. Does this one maybe respond to POST requests?

**Comment by johan-de-jong** [comment]
/datastructure is the HTML web interface. 

For the JSON data a GET /sensordata.json is needed. A POST /sensordata.json does not work (time-out).

**Comment by johan-de-jong** [comment]
My Venta devices announce themselves by by broadcasting to port udp/48000. Theoretically it could be used for auto-discovery. For example:
 
<pre>{
	"Header":{
		"DeviceType":150,
		"IpAdress":"www.xxx.yyy.zzz",
		"MacAdress":"40:91:51:xx:xx:xx",
		"ProtocolV":"3"
	}
}</pre>



<pre>{"Header":{"DeviceType":500,"MacAdress":"40:91:51:xx:xx:xx","IpAdress":"www.xxx.yyy.zzz","ProtocolV":"3.0"}}</pre>

**Comment by Michsior14** [comment]
Please try again with the latest beta. 

Regarding discovery, I researched a bit a few days ago and it looked like homeassistant doesn't support custom UDP discovery. If this is not true please link some articles ;)

**Comment by johan-de-jong** [comment]
I tried the latest beta. I tried both (protocol) auto discovery and v3. the software still seems to request POST /api/telemetry instead of GET /sensordata.json

I can not add the AirSense 150 Pro, I get an "Failed to connect" error message.

I wonder if @pontos-dev has the AirSense 100 Eco or also the AirSense 150 Pro. As far as I know it's basically the same device, except the pro has more sensors.

**Comment by Michsior14** [comment]
Strangely, this should automatically detect the proper endpoint. I guess that the issue of response types we get from the `telemetry` endpoint. Could you  add the whole response (with status, body and headers) for both telemetry and sensor.json?

**Comment by johan-de-jong** [comment]
I chose add integration and captured the traffic between home assistant and the Venta AirSense 150 Pro. I captured all the traffic in a .pcap file. I can mail it to you. I am not allowed to attach a .pcap file here.

All I see is:

<pre>POST /api/telemetry HTTP/1.1
Host: airsense-xxxxx123.fritz.box
User-Agent: HomeAssistant/2024.2.3 aiohttp/3.9.3 Python/3.12
Accept: */*
Accept-Encoding: gzip, deflate, br
Content-Length: 0
Content-Type: application/octet-stream</pre>

**Comment by Michsior14** [comment]
The hang situation would explain a lot. Will try to resolve it tomorrow ;)

**Comment by Michsior14** [comment]
Hopefully the latest beta resolves the issues with timeouts.

**Comment by johan-de-jong** [comment]
I tried adding my AirSense with:
- API version Auto Discovery I get a "Cannot determine API version" error.
- API version v3 I get a "Failed to connect" error.

A network capture shows:

<pre>GET /sensordata.json HTTP/1.1
Host: airsense-xxxxx123.fritz.box
User-Agent: HomeAssistant/2024.2.3 aiohttp/3.9.3 Python/3.12
Accept: */*
Accept-Encoding: gzip, deflate, br

HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 556
Connection: Keep-Alive

{
	"Header":{
		"DeviceId":"40:91:51:xx:xx:xx",
		"DeviceType":150,
		"ProtocolV":"3"
	},
	"Info":{
		"FirmwareVersion":"0.2-cb32b89-Nov 16 2021",
		"CertificateSHA1":"191ebc14e6b0d72785da806bc0f52e57a3258e59"
	},
	"Measure":{
		"Time":1708846541,
		"Temperature":18.55,
		"Humidity":53.23,
		"Co2":708.00,
		"Voc":64.00,
		"Hcho":3.60,
		"Pm1u0":0.00,
		"Pm2u5":0.00,
		"Pm10u":0.00,
		"Particles0u3":17.00,
		"Particles0u5":6.00,
		"Particles1u0":1.00,
		"Particles2u5":0.00,
		"Particles5u0":0.00,
		"Particles10u":0.00,
		"SensorStatus":"0000001F"
	}
}POST /datastructure HTTP/1.1
Host: airsense-xxxxx123.fritz.box
User-Agent: HomeAssistant/2024.2.3 aiohttp/3.9.3 Python/3.12
Accept: */*
Accept-Encoding: gzip, deflate, br
Content-Length: 0
Content-Type: application/octet-stream</pre> 

The first GET /sensordata.json request works. The second POST /datastructure request seems to hang forever.

**Comment by Michsior14** [comment]
I think that was the issue of venta returning (once again) wrong `content-type` with json response. I've fixed it to completely disable such validation. Hope this helps ;)

**Comment by johan-de-jong** [comment]
Using Add Integration - Venta, I can now add the AirSense.

The integration shows the AirSense, but has no devices or entities. I enabled debug logging and collected the output below:

<pre>2024-02-25 12:30:27.091 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 12:30:32.095 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 12:30:32.168 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 12:30:32.237 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: AirSense-AABEE756.fritz.box
2024-02-25 12:30:32.238 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 12:30:32.301 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.063 seconds (success: True)
2024-02-25 12:30:32.312 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up venta platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/venta/binary_sensor.py", line 86, in async_setup_entry
    entities = [
               ^
TypeError: 'NoneType' object is not iterable
2024-02-25 12:30:32.319 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform venta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 642, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 559, in async_get_or_create
    connections = _normalize_connections(connections)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1110, in _normalize_connections
    (key, format_mac(value)) if key == CONNECTION_NETWORK_MAC else (key, value)
          ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 327, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-02-25 12:30:32.327 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up venta platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 642, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 559, in async_get_or_create
    connections = _normalize_connections(connections)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1110, in _normalize_connections
    (key, format_mac(value)) if key == CONNECTION_NETWORK_MAC else (key, value)
          ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 327, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()</pre>

**Comment by johan-de-jong** [comment]
I've removed the AirSense device (and left both Humidifiers untouched), updated the integration, restarted and re-added the AirSense.

The integration shows the AirSense, but has no devices or entities.

<pre>2024-02-25 13:52:07.737 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:52:07.738 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:52:15.098 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-slaapkamer.fritz.box
2024-02-25 13:52:15.098 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:52:15.104 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-woonkamer.fritz.box
2024-02-25 13:52:15.104 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:52:15.539 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.441 seconds (success: True)
2024-02-25 13:52:15.543 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.440 seconds (success: True)
2024-02-25 13:52:16.240 ERROR (MainThread) [homeassistant.components.select] Error while setting up venta platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/venta/select.py", line 79, in async_setup_entry
    if description.key in description.exists_func(coordinator)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable
2024-02-25 13:52:16.276 ERROR (MainThread) [homeassistant.components.select] Error while setting up venta platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/venta/select.py", line 79, in async_setup_entry
    if description.key in description.exists_func(coordinator)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable
2024-02-25 13:52:17.459 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:52:24.234 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 13:52:24.571 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 13:52:24.686 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 13:52:24.743 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: AirSense-xxxxx123.fritz.box
2024-02-25 13:52:24.743 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 13:52:24.811 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.067 seconds (success: True)
2024-02-25 13:52:24.822 ERROR (MainThread) [homeassistant.components.select] Error while setting up venta platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/venta/select.py", line 79, in async_setup_entry
    if description.key in description.exists_func(coordinator)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable
2024-02-25 13:52:24.832 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform venta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 642, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 559, in async_get_or_create
    connections = _normalize_connections(connections)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1110, in _normalize_connections
    (key, format_mac(value)) if key == CONNECTION_NETWORK_MAC else (key, value)
          ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 327, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-02-25 13:52:24.848 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up venta platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 642, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 559, in async_get_or_create
    connections = _normalize_connections(connections)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1110, in _normalize_connections
    (key, format_mac(value)) if key == CONNECTION_NETWORK_MAC else (key, value)
          ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 327, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-02-25 13:52:46.559 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-slaapkamer.fritz.box
2024-02-25 13:52:46.560 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:52:46.617 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-woonkamer.fritz.box
2024-02-25 13:52:46.618 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:52:46.651 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.091 seconds (success: True)
2024-02-25 13:52:46.989 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.371 seconds (success: True)
2024-02-25 13:53:16.559 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-slaapkamer.fritz.box
2024-02-25 13:53:16.560 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:53:16.618 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-woonkamer.fritz.box
2024-02-25 13:53:16.618 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:53:16.658 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.099 seconds (success: True)
2024-02-25 13:53:16.667 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.050 seconds (success: True)
2024-02-25 13:53:46.559 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-slaapkamer.fritz.box
2024-02-25 13:53:46.560 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:53:46.617 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-woonkamer.fritz.box
2024-02-25 13:53:46.618 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:53:46.960 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.401 seconds (success: True)
2024-02-25 13:53:46.996 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.378 seconds (success: True)
2024-02-25 13:54:16.560 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-slaapkamer.fritz.box
2024-02-25 13:54:16.560 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:54:16.617 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: venta-woonkamer.fritz.box
2024-02-25 13:54:16.618 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to api/telemetry with data: None
2024-02-25 13:54:16.662 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.045 seconds (success: True)
2024-02-25 13:54:16.674 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.114 seconds (success: True)</pre>

**Comment by Michsior14** [comment]
Sorry for such high number of builds... Some refactors did not go as planed. Would be probably the best to finally introduce some tests ;)

**Comment by johan-de-jong** [comment]
No problem. I very much appreciate your effort! And I am glad to help test your integration.

To me the integration is very useful as the Venta Home app does not support push notifications for e.g. when the water needs to be refilled or the room needs to be ventilated.

I hope Venta will continue to develop the Venta Home app and firmware for the different devices. I would very much like to be able to dim the light of my AirSense when I am sleeping. Right now this is not supported.

**Comment by Michsior14** [comment]
I didn't mention it but there has been a beta.6 released. Please check if it loads properly.

**Comment by johan-de-jong** [comment]
The integration shows the AirSense, but has no devices or entities.

Below I deleted the AirSense device and re-added it. It shows the errors below only once, when adding the device. When I restart Home Assistant it does not show the errors again.

<pre>2024-02-25 14:53:20.308 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 14:53:20.372 DEBUG (MainThread) [custom_components.venta.venta] Polling Venta device: AirSense-xxxxx123.fritz.box
2024-02-25 14:53:20.372 DEBUG (MainThread) [custom_components.venta.venta_strategy] Sending request to sensordata.json with data: None
2024-02-25 14:53:20.431 DEBUG (MainThread) [custom_components.venta.venta] Finished fetching venta data in 0.060 seconds (success: True)
2024-02-25 14:53:20.447 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform venta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 642, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 559, in async_get_or_create
    connections = _normalize_connections(connections)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1110, in _normalize_connections
    (key, format_mac(value)) if key == CONNECTION_NETWORK_MAC else (key, value)
          ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 327, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-02-25 14:53:20.454 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up venta platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 642, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 559, in async_get_or_create
    connections = _normalize_connections(connections)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1110, in _normalize_connections
    (key, format_mac(value)) if key == CONNECTION_NETWORK_MAC else (key, value)
          ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 327, in format_mac
    if len(to_test) == 17 and to_test.count(":") == 5:
       ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()</pre>

**Comment by Michsior14** [comment]
Ok, mac address should be properly recognized now. They really do use totally different properties across devices...

**Comment by johan-de-jong** [comment]
There are no more errors in the log; and this looks almost perfect! Instead of Formaldehyde it prints None. Is the temperature rounded to a whole number? The API reports 2 digits after the separator.

![image](https://github.com/Michsior14/ha-venta/assets/38002717/fec417db-16b8-4691-98ff-29c4e6e028a5)

**Comment by Michsior14** [comment]
The translation key has been fixed. Regarding temperature rounding, I've aligned it with the defaults of HA (1 digit after comma). If you want to change it to 2 digits you can do so in the sensor settings.

**Comment by johan-de-jong** [comment]
Everything looks good now. Thank you!

**Comment by johan-de-jong** [comment]
I have a strong suspicion that even though the Venta Home app reports the VOC in **ppb**, it's probably the Sensirion’s VOC Index instead. [https://sensirion.com/media/documents/02232963/6294E043/Info_Note_VOC_Index.pdf](https://sensirion.com/media/documents/02232963/6294E043/Info_Note_VOC_Index.pdf)

The Sensirion VOC Index is a number from 1 to 500; where 100 represents an average amount of VOC's in the last 24 hours. A value below 100 means better than average. A value higher than 100 means worse than average.

The Sensirion VOC Index can never be '0' (zero).

When you look at the graph below it shows the max/min/mean (average) values. The light blue frequently dips too deep to '0'.

I feel this is probably another firmware quirk. I think that when the sensor is not ready it sometimes reports '0' when it should have reported 'None'.

Would you consider ignoring value '0' for the VOC sensor? That would that the graph is broken when no valid measurement is available for a specific time.

Or ignore value '0' and use the previous valid value again instead?

![image](https://github.com/Michsior14/ha-venta/assets/38002717/9baafa53-63d2-4e02-bc83-4636371ff199)

The CO2, Formaldehyde and Temperature sensors have the same issue. Sometimes (but less frequently than for the VOC sensor) a false value '0' is reported when it should have been a 'None' instead. Since '0' is an unlikely valid value for these sensors, perhaps you could apply the same fix for these sensors?

The particle count and PM sensors undoubtedly have the same issue, but since these sensors can produce a valid '0' value these sensors are better left untouched.
